// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	api "github.com/luxfi/netrunner/api"
	admin "github.com/luxfi/sdk/admin"

	exchangevm "github.com/luxfi/sdk/exchangevm"

	indexer "github.com/luxfi/sdk/indexer"

	sdkinfo "github.com/luxfi/sdk/info"

	mock "github.com/stretchr/testify/mock"

	platformvm "github.com/luxfi/sdk/platformvm"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AdminAPI provides a mock function with given fields:
func (_m *Client) AdminAPI() *admin.Client {
	ret := _m.Called()

	var r0 *admin.Client
	if rf, ok := ret.Get(0).(func() *admin.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Client)
		}
	}

	return r0
}

// CChainAPI provides a mock function with given fields:
func (_m *Client) CChainAPI() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0)
	}

	return r0
}

// CChainEthAPI provides a mock function with given fields:
func (_m *Client) CChainEthAPI() api.EthClient {
	ret := _m.Called()

	var r0 api.EthClient
	if rf, ok := ret.Get(0).(func() api.EthClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.EthClient)
		}
	}

	return r0
}

// CChainIndexAPI provides a mock function with given fields:
func (_m *Client) CChainIndexAPI() *indexer.Client {
	ret := _m.Called()

	var r0 *indexer.Client
	if rf, ok := ret.Get(0).(func() *indexer.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Client)
		}
	}

	return r0
}

// HealthAPI provides a mock function with given fields:
func (_m *Client) HealthAPI() api.HealthClient {
	ret := _m.Called()

	var r0 api.HealthClient
	if rf, ok := ret.Get(0).(func() api.HealthClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.HealthClient)
		}
	}

	return r0
}

// InfoAPI provides a mock function with given fields:
func (_m *Client) InfoAPI() *sdkinfo.Client {
	ret := _m.Called()

	var r0 *sdkinfo.Client
	if rf, ok := ret.Get(0).(func() *sdkinfo.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdkinfo.Client)
		}
	}

	return r0
}

// PChainAPI provides a mock function with given fields:
func (_m *Client) PChainAPI() *platformvm.Client {
	ret := _m.Called()

	var r0 *platformvm.Client
	if rf, ok := ret.Get(0).(func() *platformvm.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformvm.Client)
		}
	}

	return r0
}

// PChainIndexAPI provides a mock function with given fields:
func (_m *Client) PChainIndexAPI() *indexer.Client {
	ret := _m.Called()

	var r0 *indexer.Client
	if rf, ok := ret.Get(0).(func() *indexer.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Client)
		}
	}

	return r0
}

// XChainAPI provides a mock function with given fields:
func (_m *Client) XChainAPI() *exchangevm.Client {
	ret := _m.Called()

	var r0 *exchangevm.Client
	if rf, ok := ret.Get(0).(func() *exchangevm.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exchangevm.Client)
		}
	}

	return r0
}

// XChainWalletAPI provides a mock function with given fields:
func (_m *Client) XChainWalletAPI() *exchangevm.WalletClient {
	ret := _m.Called()

	var r0 *exchangevm.WalletClient
	if rf, ok := ret.Get(0).(func() *exchangevm.WalletClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exchangevm.WalletClient)
		}
	}

	return r0
}
